# Generated by Django 4.1.7 on 2023-04-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0002_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='amount',
        ),
    ]
