# Generated by Django 4.1.7 on 2023-04-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0003_delete_uploadimage_rename_phone_customer_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='amount',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='customer',
            name='bonus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='deposit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='plan',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
