# Generated by Django 4.1.7 on 2023-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0005_rename_balance_customer_phone_remove_customer_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
