# Generated by Django 4.1.7 on 2023-04-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0006_customer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bonus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='deposit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='plan',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
