# Generated by Django 4.1.7 on 2023-04-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0007_customer_bonus_customer_deposit_customer_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='oohhi_WEUW1TN.png', null=True, upload_to=''),
        ),
    ]
