# Generated by Django 4.1.7 on 2023-04-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0008_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount',
            field=models.CharField(default='10,000', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bonus',
            field=models.CharField(default='10,000', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='deposit',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='plan',
            field=models.CharField(default='Plan1', max_length=200, null=True),
        ),
    ]
